[project]
name = "vkposterbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiogram==2.9.2",
    "aiohttp>=3.11.16",
]
